language: ruby

env:
- JOB=job1
- JOB=job2
- JOB=job3

install: true

before_script:
  - echo "Hello, world!"
  - echo "This is build $TRAVIS_BUILD_ID, and this is job $JOB_ID and $JOB and $TRAVIS_TOKEN"
  - if [[ "$JOB" == "job2" ]]; then sleep 160; fi
  - if [[ "$JOB" == "job3" ]]; then sleep 260; fi
  
script:
  - "curl -X POST -H \"Travis-API-Version: 3\" -H \"User-Agent: MyExample\" -H \"Authorization: token $TRAVIS_TOKEN\"  \"https://api.travis-ci.org/build/$TRAVIS_BUILD_ID/cancel\""
