language: ruby

before_install: 
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then if [ "${TRAVIS_BRANCH}" != "master" ]; travis_terminate 0; fi fi
 

install: true

script:
  - echo "Hello, world!"
  - date "+%H:%M:%S   %d/%m/%y"
